---
deployment:
  tasks:
    # Retirez ou commentez la ligne "npm install"
    # - /bin/bash -c "npm install"  <-- À RETIRER
    
    # 1. Construire l'application
    - /bin/bash -c "npm run build"
    
    # 2. Copier les fichiers construits vers le sous-dossier 'app'
    - /bin/bash -c "rsync -av --exclude 'app' . /home/umdynastie/educwaly/app"