---
deployment:
  tasks:
    - export DEPLOYPATH=/home/umdynastie/site/educwaly/app
    - /bin/bash -c "npm install"
    - /bin/bash -c "npm run build"
    # cPanel va exécuter ces commandes après chaque pull